##############################################
#### _____                 __  _          ####
####/  __ \               / _|(_)         ####
####| /  \/  ___   _ __  | |_  _   __ _   ####
####| |     / _ \ | '_ \ |  _|| | / _` |  ####
####| \__/\| (_) || | | || |  | || (_| |  ####
#### \____/ \___/ |_| |_||_|  |_| \__, |  ####
####                               __/ |  ####
####                              |___/   ####
##############################################


##############
#   Window   #
##############
[window]

padding = {x = 15, y = 10}
opacity = 1
# decorations = "none"


############
#   Font   #
############
[font]

size = 12
normal = {family = "Hack Nerdfont", style = "Regular"}
bold = {family = "Hack Nerdfont", style = "Bold"}
italic = {family = "Hack Nerdfont", style = "Italic"}


##############
#   Colors   #
##############
[colors.normal]

black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#ebdbb2"

[colors.bright]

black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"
